In one of the videos there is a library called dbplyr.  It is a library similar to dplyr but it is used with databases.  
I have not seen it before and wanted to give it a try.  I ran the queries in SQL and dbplyr.  
Found some interesting things with the basic test I did which I will comment at the end.

#--------- CODE ------------------------

library(DBI)
library(magrittr)
library(tidyverse)

#create new dataframe
location <- c("US", "Puerto Rico", "Egypt", "Mozambique", "Barbados", "Mexico")
longitude <- c(-98.35,-66.105,30.80,35.52, -59.54, -99.13)
latitude <- c(39.50,18.46,26.82,-25.95, 13.19, 19.43)

data511_loc <-data.frame(location, longitude, latitude)

con <- dbConnect(RSQLite::SQLite(), ":memory:")

#prepare table to use sql
dbWriteTable(con, "data511_loc", data511_loc)
dbListTables(con)

#prepare table to use dbplyr
data511_loc_dbplyr <- tbl(con, "data511_loc")

#SQL version
loc_result <- dbGetQuery(con, "SELECT location FROM data511_loc")
loc_result
#dbplyr version
loc_dbplyr <- data511_loc_dbplyr %>%
  select(location)
loc_dbplyr %>% collect()

#SQL Version
loc_lat_result <- dbGetQuery(con, "SELECT location, latitude FROM data511_loc where latitude < 0")
loc_lat_result

#dbplyr version
loc_lat_dbplyr_result <- data511_loc_dbplyr %>%
  select(location, latitude) %>%
  filter (latitude < 0)
loc_lat_dbplyr_result %>% collect()

#View SQL generated by dbplyr for the last query
loc_lat_dbplyr_result %>% show_query()

#This is a nice trick to learn SQL if you know how to use the dplyr functions

dbDisconnect(con)

#------------------------------------------

Important output sections when the code runs:

> #SQL version
> loc_result <- dbGetQuery(con, "SELECT location FROM data511_loc")
> loc_result
     location
1          US
2 Puerto Rico
3       Egypt
4  Mozambique
5    Barbados
6      Mexico
> #dbplyr version
> loc_dbplyr <- data511_loc_dbplyr %>%
+   select(location)
> loc_dbplyr %>% collect()
# A tibble: 6 × 1
  location   
  <chr>      
1 US         
2 Puerto Rico
3 Egypt      
4 Mozambique 
5 Barbados   
6 Mexico     
> 
> #SQL Version
> loc_lat_result <- dbGetQuery(con, "SELECT location, latitude FROM data511_loc where latitude < 0")
> loc_lat_result
    location latitude
1 Mozambique   -25.95
> 
> #dbplyr version
> loc_lat_dbplyr_result <- data511_loc_dbplyr %>%
+   select(location, latitude) %>%
+   filter (latitude < 0)
> loc_lat_dbplyr_result %>% collect()
# A tibble: 1 × 2
  location   latitude
  <chr>         <dbl>
1 Mozambique    -26.0
> 
> #View SQL generated by dbplyr for the last query
> loc_lat_dbplyr_result %>% show_query()
<SQL>
SELECT *
FROM (SELECT `location`, `latitude`
FROM `data511_loc`)
WHERE (`latitude` < 0.0)
> 


COMMENTS:

1 - Looks like the output from a SQL query is straight text and from dbplyr is a tibble.  A tibble is a "Souped up or suped up" version of a dataframe.

2 - The SQL query returned the exact latitude for Mozambique: -25.95.  The dbplyr query rounded to -26.  That could be a big problem.  Maybe there are some settings that I do not know of.

3 - In order to get the data from dbplyr you have to call collect().  This is call lazy loading

4 - This one is good or bad depending if you want to learn or if performance is important.  For dbplyr you can call show_query() to show the SQL if you want to learn SQL but the result it gave in this example I did not like.

The result should have been:

SELECT `location`, `latitude`
FROM `data511_loc`
WHERE (`latitude` < 0.0)  

which is a basic query, but it gave:

SELECT *
FROM (SELECT `location`, `latitude`
FROM `data511_loc`)
WHERE (`latitude` < 0.0)

It created a subquery inside the main query and this leads to bad performance.  Maybe there is a guideline provided to create better queries.
